### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by aheadzen** [rajeshwarpatlolla/ionic-timepicker#51]
Hello,

Component creates css style in index.html just below the included js file. Problem is with using classname same as core ionic css classes. It is creating unnecessary css issues for our app. Can we use more specific class names to prevent style conflicts

``` css
.bar.bar-stable, .tabs {
    box-shadow: 0 0 5px #555;
}
```
