### ISSUE TITLE
It can not change button css

### ISSUE THREAD

**Issue by huigesv123** [rajeshwarpatlolla/ionic-timepicker#84]
I have set button_set class

.button_set{
  background-color: #0a9dc7;
}

but it doesn't work

I even change ionic-timepicker.style.css, then got the same result

**Comment by cklaffer** [comment]
+1

**Comment by arvindr21** [comment]
try this override in your css/scss file

``` css
.ionic_timepicker_popup .heading{
    background-color: #1b83b9 !important;
}

.ionic_timepicker_popup .button_set, .ionic_timepicker_popup .button_close{
    background-color: #1b83b9 !important;
}
```
